feat: add option for bearer token
obiba/resourcer pull request #11
Opened 2023-04-12 20:54 UTC by mswertz

Would this make sense? Is untested so just meant to start discussion

2023-04-13 07:19 UTC, ymarcon requested changes

2023-04-13 07:19 UTC, ymarcon commented on R/HttpFileResourceGetter.R
> +	        httr::add_headers(Authorization = jsonlite::base64_enc(paste0("Bearer",resource$secret)))
A whitespace is missing between the Bearer and the secret.

2023-04-13 07:24 UTC, ymarcon commented on R/HttpFileResourceGetter.R
> +	        httr::add_headers(Authorization = jsonlite::base64_enc(paste0("Bearer",resource$secret)))
And it is just the secret that needs to be base64 encoded.

2023-04-18 16:33 UTC, ymarcon requested changes

2023-04-18 16:33 UTC, ymarcon commented on R/HttpFileResourceGetter.R
> +	httr::add_headers(Authorization = paste0("Bearer", resource$secret))
Whitespace is still missing after "Bearer", I would expect: `paste0("Bearer ", resource$secret)`

2023-04-21 09:23 UTC, mswertz commented on R/HttpFileResourceGetter.R
> +	httr::add_headers(Authorization = paste0("Bearer", resource$secret))
Great, done.

2023-04-21 11:13 UTC, ymarcon approved these changes

2023-04-21 11:13 UTC, merged